id: PA7774877
initial_creation_type: ocr
source_metadata:
  volumes:
    6878cef35216437980fe029ad3733328:
      base_file: v074.txt
      image_group_id: I1PD95919
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་རྣམ་པར་གཏན་ལ་དབབ་པ་བསྡུ་བ།
      total_pages: 1618
      volume_number: 74
